Repository shutterberg/c-, pull requests merged in 2022-10, with the labels that each got.

#2 Implementing Stack in C
  stack.c
Labels: hacktoberfest, hacktoberfest-accepted

#3 COMMIT 1
  q3.py
Labels: hacktoberfest, hacktoberfest-accepted

#4 ASCII
  ascii.c
Labels: documentation, hacktoberfest, hacktoberfest-accepted

#5 DEC TO BIN CONVERT
  decToBin.c
Labels: bug, help wanted, hacktoberfest, hacktoberfest-accepted

#6 REV DIGITS
  revDigits.c
Labels: hacktoberfest, hacktoberfest-accepted

#8 SUM OF DIGITS
  sumDigits.c
Labels: hacktoberfest, hacktoberfest-accepted

#9 PASCAL TRIANGLE IMPLEMENTATION
  pascalTriangle.c
Labels: hacktoberfest, hacktoberfest-accepted

#10 Octal to dec convert
  octalToDec.c
Labels: hacktoberfest, hacktoberfest-accepted

#11 DEC INT CONVERT
  intToDec.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#13 Added c code to remove duplicate elements
  removeDuplicates.c
Labels: hacktoberfest, hacktoberfest-accepted

#14 Added c code to multiply given matrixes
  matrixMultiply.c
Labels: hacktoberfest, hacktoberfest-accepted

#15 Added c code to concate strings using pointer
  concatStrings.c
Labels: hacktoberfest, hacktoberfest-accepted

#17 Added c code to find the first N prime nums
  firstNprimeNums.c
  power.c
Labels: hacktoberfest, hacktoberfest-accepted

#18 Added c code to swap 2 numbers
  swap.c
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#19 Palindrome of a number commit
  palindrome.c
Labels: hacktoberfest, hacktoberfest-accepted

#20 Program for armstrong number commit
  armstrong.c
Labels: documentation, hacktoberfest, hacktoberfest-accepted

#21 commit program for automorphic
  automorphic.c
Labels: help wanted, hacktoberfest, hacktoberfest-accepted

#22 Anagram of number program commit
  anagram.c
Labels: hacktoberfest, hacktoberfest-accepted

#23 Added lexicographic Sort program
  SelectionSort.c
  lexicographicSort.c
Labels: hacktoberfest, hacktoberfest-accepted

#24 Committed bubble sort
  bubbleSort.c
Labels: hacktoberfest, hacktoberfest-accepted

#25 Added Quick Sort Algorithm
  quickSort.c
Labels: hacktoberfest, hacktoberfest-accepted

#26 Merge Sort Algorithm Added
  mergeSort.c
Labels: hacktoberfest, hacktoberfest-accepted
